version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependencias..."
  pre_build:
    commands:
      - echo "Preparando deploy..."
      - INSTANCE_ID="i-04fb984b5ce6d529f"
  build:
    commands:
      - echo "Enviando comandos para a EC2 via SSM..."
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "set -e",
              "cd /home/ec2-user",
              "if [ ! -d \"app\" ]; then git clone https://github.com/brunonoatto/autolog-dotnet-api app; fi",
              "cd app",
              "git pull origin main",
              "echo \"DB_PASSWORD=${DB_PASSWORD}\" > .env",
              "echo \"DB_NAME=${DB_NAME}\" >> .env",
              "echo \"DB_USER=${DB_USER}\" >> .env",
              "echo \"HASH_SALT=${HASH_SALT}\" >> .env",
              "echo \"HASH_JWT_KEY=${HASH_JWT_KEY}\" >> .env",
              "export DOCKER_BUILDKIT=0",
              "export COMPOSE_DOCKER_CLI_BUILD=0",
              "sudo docker build -t app-api -f Dockerfile .",
              "sudo /usr/local/bin/docker-compose -f docker-compose.prod.yml up -d",
              "sudo docker image prune -f"
            ]
          }' \
          --region us-east-1
