version: 0.2

phases:
  install:
    commands:
      - echo "Instalando dependências se necessário..."
  pre_build:
    commands:
      - echo "Preparando para o deploy..."
      # Substitua pelo ID da sua instância EC2
      - INSTANCE_ID="i-04fb984b5ce6d529f"
  build:
    commands:
      - echo "Enviando comandos para a EC2 via SSM..."
      - |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "set -e",
              "cd /home/ec2-user",
              "if [ ! -d \"app\" ]; then git clone https://github.com/brunonoatto/autolog-dotnet-api app; fi",
              "cd app",
              "git pull origin main",
              "echo \"DB_PASSWORD=${DB_PASSWORD}\" > .env",
              "sudo /usr/local/bin/docker-compose -f docker-compose.prod.yml up -d --build",
              "sudo docker image prune -f"
            ]
          }' \
          --region us-east-1
